$ python3 or_button_interrupt.py 
Starting demo now! Press CTRL+C to exit
main
main
main
Blink
main
main
main
main
^C^CTraceback (most recent call last):
  File "or_button_interrupt.py", line 55, in main
    time.sleep(2)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "or_button_interrupt.py", line 61, in <module>
    main()

==========================================
started a 2nd time.


$ python or_button_interrupt.py 
/usr/local/lib/python2.7/dist-packages/Jetson/GPIO/gpio.py:228: RuntimeWarning: This channel is already in use, continuing anyway. Use GPIO.setwarnings(False) to disable warnings
  RuntimeWarning)
Starting demo now! Press CTRL+C to exit
main
main

